#:schema https://starship.rs/config-schema.json

format = """
$username($git_branch$git_status)$directory\
$fill\
($rust)\
($conda)\
($python)\
$line_break\
$character
"""

add_newline = false

[username]
show_always = true
format = '[ $user ](fg:#212736 bg:#769ff0)'

[git_branch]
format = "[ $symbol $branch(:$remote_branch)](fg:#769ff0 bg:#394260)"
symbol = ""

[git_status]
up_to_date = "✔"
format = "[$all_status$ahead_behind ](fg:#769ff0 bg:#394260)"
style = "purple bold"

[directory]
style = 'bg:#212736'
format = '[ $path ]($style)[$read_only]($read_only_style)'
truncate_to_repo = false
truncation_symbol = '…/'
truncation_length = 3

[fill]
symbol = " "

[rust]
format = "[ $symbol($version)( $toolchain) ]($style bg:#212736)"

[conda]
format = "[ $symbol $environment ]($style bg:#212736)"

[python]
format = "[ ${symbol}${pyenv_prefix}(${version})( \\($virtualenv\\)) ]($style bg:#212736)"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
